on:
  workflow_dispatch:
    inputs:
      dockerfileVersion:
        required: true
        type: string
        default: 1.5.1
      graphdbVersion:
        required: true
        type: string
      latest:
        required: true
        type: boolean

jobs:
    build-amd64:
        runs-on: [self-hosted, "X64"]
        steps:

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Get latest code
          uses: actions/checkout@v3

        - name: Checkout the tag
          run: |
            git fetch --all
            git checkout v${{ inputs.dockerfileVersion }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            no-cache: true
            push: true
            pull: true
            tags: "khaller/graphdb-free-test:${{ inputs.dockerfileVersion }}-graphdb${{ inputs.graphdbVersion }}_amd64"
            build-args: |
              GDB_VERSION=${{ inputs.graphdbVersion }}
              DFILE_VERSION=${{ inputs.dockerfileVersion }}

